version: '3.7'

services:
  customer:
    container_name: klinify_customer
    build: ./services/customer
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./services/customer/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=klinify
      - POSTGRES_PASSWORD=klinify
      - POSTGRES_DB=customer_table
  redis:
    image: "redis:alpine"

volumes:
  postgres_data: