version: '3.7'

services:
  customer:
    build:
      context: ./services/customer
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=klinify
      - POSTGRES_PASSWORD=klinify
      - POSTGRES_DB=customer_table
  redis:
    image: "redis:alpine"

volumes:
  postgres_data: