version: '3.7'

services:
  customer:
    container_name: klinify_customer
    build: ./services/customer
    # docker compose for dev, auto generates some dummy data for testing
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./services/customer/:/usr/src/app/
    ports:
      - 5000:5000
    # important things are kept in the env file
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=klinify
      - POSTGRES_PASSWORD=klinify
      - POSTGRES_DB=customer_table
  redis:
    image: "redis:alpine"
    ports:
     - 6379:6379
    # start redis
    command:
      redis-server


volumes:
  postgres_data: